name: Github actions test
on: [push]
jobs:
    SSH_and_Build:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: SSH & Build
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            cd dreammart.wisedev.xyz
            git fetch && git pull
            npm i
            npm run build